### ISSUE TITLE
framework almost the same as another one

### ISSUE THREAD

**Issue by QiaoranC** [ZhixinLai/LLMBoostMedical#4]
The framework appears to have no major difference from "FROZEN TRANSFORMERS IN LANGUAGE MODELS ARE EFFECTIVE VISUAL ENCODER LAYERS". Even the pseudo-code seems identical. And the conclusion seems highly similar. I mean, is there anything new to be found?

![截屏2024-03-28 09 53 55](https://github.com/ZhixinLai/LLMBoostMedical/assets/29221630/2685c503-358c-4fa5-b0ba-c1fc165628b8)

**Comment by ZhixinLai** [comment]
> The framework appears to have no major difference from "FROZEN TRANSFORMERS IN LANGUAGE MODELS ARE EFFECTIVE VISUAL ENCODER LAYERS". Even the pseudo-code seems identical. And the conclusion seems highly similar. I mean, is there anything new to be found?
> 
> ![截屏2024-03-28 09 53 55](https://private-user-images.githubusercontent.com/29221630/317565369-2685c503-358c-4fa5-b0ba-c1fc165628b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MDYwODMsIm5iZiI6MTcxMTYwNTc4MywicGF0aCI6Ii8yOTIyMTYzMC8zMTc1NjUzNjktMjY4NWM1MDMtMzU4Yy00ZmE1LWIwYmEtYzFmYzE2NTYyOGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA2MDMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YmUyNDJlOWU2YTNiZTU0ODNkNTBjMjRmZmE3M2M1NjE4MjZjNWQ4ODQ0ZWJlNGU0OWM1MDM2MWVkYTk5MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wHRr1ZXFmytinAQVlt1xUN6CE6e86qV799lVobhAVfc)

Thanks for the attention! [LM4VisualEncoding](https://github.com/ziqipang/LM4VisualEncoding) alongside the paper [Frozen Transformers in Language Models are Effective Visual Encoder Layers](https://arxiv.org/abs/2310.12973) have been pivotal in shaping our approach. Drawing upon their insights, we adapted and expanded upon the 2D image classification framework to accommodate both 2D and 3D medical imaging data, experimenting with various configurations of residual blocks to enhance the model's performance on the medical image dataset. This repo mainly focuses on medical image applications.

**Comment by ZhixinLai** [comment]
Thanks for the attention! [LM4VisualEncoding](https://github.com/ziqipang/LM4VisualEncoding) alongside the paper [Frozen Transformers in Language Models are Effective Visual Encoder Layers](https://arxiv.org/abs/2310.12973) have been pivotal in shaping our approach. Drawing upon their insights, we adapted and expanded upon the 2D image classification framework to accommodate both 2D and 3D medical imaging data, experimenting with various configurations of residual blocks to enhance the model's performance on the medical image dataset. This repo mainly focuses on medical image applications.
