### ISSUE TITLE
LM4VisualEncoding

### ISSUE THREAD

**Issue by daydayupzzl** [ZhixinLai/LLMBoostMedical#5]
https://github.com/ziqipang/LM4VisualEncoding what is the difference
![image](https://github.com/ZhixinLai/LLMBoostMedical/assets/69570655/f3cc42e2-6f34-40d5-8f7f-e6c8f26a88c3)

**Comment by ZhixinLai** [comment]
> https://github.com/ziqipang/LM4VisualEncoding what is the difference ![image](https://private-user-images.githubusercontent.com/69570655/317567487-f3cc42e2-6f34-40d5-8f7f-e6c8f26a88c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MDU5MDUsIm5iZiI6MTcxMTYwNTYwNSwicGF0aCI6Ii82OTU3MDY1NS8zMTc1Njc0ODctZjNjYzQyZTItNmYzNC00MGQ1LThmN2YtZTZjOGYyNmE4OGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA2MDAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNmIwNWVhYTY4YzVlYzI4YjgzMTk3ZmI1MTM2YTk4MGQxM2UxMWRiNzg3NzkxNWEwNmJiNzBjMTk2MDE1NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H1k1OIPjThPFlSBAyUr_U3iTWsqTH06qvirWvoCCy6Y)

Thanks for the attention! [LM4VisualEncoding](https://github.com/ziqipang/LM4VisualEncoding) alongside the paper [Frozen Transformers in Language Models are Effective Visual Encoder Layers](https://arxiv.org/abs/2310.12973) have been pivotal in shaping our approach. Drawing upon their insights, we adapted and expanded upon the 2D image classification framework to accommodate both 2D and 3D medical imaging data, experimenting with various configurations of residual blocks to enhance the model's performance on the medical image dataset. This repo mainly focuses on medical image applications.

**Comment by ZhixinLai** [comment]
Thanks for the attention! [LM4VisualEncoding](https://github.com/ziqipang/LM4VisualEncoding) alongside the paper [Frozen Transformers in Language Models are Effective Visual Encoder Layers](https://arxiv.org/abs/2310.12973) have been pivotal in shaping our approach. Drawing upon their insights, we adapted and expanded upon the 2D image classification framework to accommodate both 2D and 3D medical imaging data, experimenting with various configurations of residual blocks to enhance the model's performance on the medical image dataset. This repo mainly focuses on medical image applications.
